### PR TITLE
add MedUI for Medievia

### PR DESCRIPTION
**Pull request by jmckisson**
This adds the user interface for the Medievia MUD

### CODE REVIEW

**Review by vadi2 — APPROVED** [review]

**Comment by ZookaOnGit** [comment]
Thanks for submitting the package @jmckisson, but this one needs a description too; either added from the Package Exporter or by manually adding one to the config.lua (refer to other packages in the repository).

The description is used when searching for a package with `mpkg` and shows up in the Package Exporter as well.

**Comment by jmckisson** [comment]
> Thanks for submitting the package @jmckisson, but this one needs a description too; either added from the Package Exporter or by manually adding one to the config.lua (refer to other packages in the repository).
> 
> The description is used when searching for a package with `mpkg` and shows up in the Package Manager as well.

Hmmm I had one at one point maybe Muddler tossed it somehow, thanks for noticing will fix!

**Comment by jmckisson** [comment]
Ok the description has been added back in, the README.md wasn't copied over correctly when I converted it to Muddler =/
One thing to note and I'm not sure if its the intention of the mpkg show command, but for an installed package (locally) mpkg show doesn't show any information about the package if it is not in the repository... I'll create an issue if if its actually supposed to show some info for a locally installed package...

**Comment by ZookaOnGit** [comment]
> mpkg show doesn't show any information about the package if it is not in the repository

yeah, true.. we don't have a command for that `mpkg show-local`?
please add an issue

**Pull request merged**
