### PR TITLE
add mpkg upgrade command

### LINKED ISSUE #42: mpkg upgrade
I've been debating whether to provide this command to give the ability to upgrade to a new version of an installed package.

Atm I have instructed the user to run `mpkg remove` first, then `mpkg install <pkg>`

This is a way to let them know that the old package will be removed and thus remind them that any changes they have made to the package will be lost.

Thoughts?

### PR DESCRIPTION
**Pull request by ZookaOnGit**
add mpkg upgrade <package_name>
move script up a sublevel in script editor
add ldocs to scripts

closes #42

### CODE REVIEW

**Review by vadi2 — APPROVED** [review]
I feel a bit blind not being able to see the changes in a diff :)

**Comment by ZookaOnGit** [comment]
do you know if github.com accepts things like this?
https://superuser.com/questions/706042/how-can-i-diff-binary-files-in-git

**Comment by vadi2** [comment]
They do it on an opt in basis for more standard formats such as 3D models, but I don't think it's possible to do it for ourselves.

Using Muddler for the package itself would work through, that is git friendly. Should we try it?

**Comment by ZookaOnGit** [comment]
will we be locking out scripters who don't use muddler, and just the package exporter?

**Comment by vadi2** [comment]
ah no only for the mpkg tool itself. The third parties we shouldn't apply this for (and we aren't auditing their code anyway yet)

**Comment by ZookaOnGit** [comment]
right, I'm with you now... added a new issue

**Pull request merged**
